export {
  BrandingTab,
  ScheduleTab,
  SecuritySettingsTab,
  CouponsTab,
  CampaignsTab,
  LoyaltyTab,
  DoctorFormTab,
  TherapistFormTab,
  TreatmentTab,
  TreatmentCategoriesTab,
  UnitTypesTab,
  InventorySettingsTab,
  MappingTab,
  OnlineBookingPaymentTab,
  MessagingSettingsTab,
  MessagingTemplatesTab,
  MessagingLogsTab,
  MessagingAutomationTab,
} from "@/pages/AdminPage";
